### ISSUE TITLE
How to skip some path of my project?

### ISSUE THREAD

**Issue by rdomga** [vishalanandl177/DRF-API-Logger#10]
Can have an configuration example of the parameter DRF_API_LOGGER_SKIP_URL_NAME?
I want to know how to skip some path in my project.
Thank you in advance

DOMGA

**Comment by vishalanandl177** [comment]
Yeah sure.

Take this example URL.

from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^posts/$', views.UserPostView.as_view(), name='user_post'),
]

In the above example you can see URL name of this API is "user_post". If
you want to skip this API to be logged into the DRF API Logger then add
this below line in settings.py file.

DRF_API_LOGGER_SKIP_URL_NAME = ["user_post"]


As you can see this variable is list type so you can add many URLs.
