### ISSUE TITLE
Logging everything

### ISSUE THREAD

**Issue by hellvix** [vishalanandl177/DRF-API-Logger#11]
I made some tests and it seems that:

> It logs all the API information for content type "application/json".

Does not seem to hold true. 

Version `drf-api-logger==1.0.5` seems to be logging all types of requests.

The `response` field is skipped, but the entry is created.

**Comment by vishalanandl177** [comment]
I'll be deploying a new version soon with this fix.

*Regards,*
Vishal Anand,
Technical Lead,
LinkedIn <https://www.linkedin.com/in/vishal-anand-530ba0b5/> | M:
+91-8009417767

**Comment by vishalanandl177** [comment]
A new version is released 1.0.6 with the fixes.
