### ISSUE TITLE
Feature to write logs into a database other than the default one 

### ISSUE THREAD

**Issue by saurabh0719** [vishalanandl177/DRF-API-Logger#17]
Hi!

Having gone through the documentation it is my understanding that logs are written into the `default` database described in the `settings.py` file. 

Is it possible to add a feature to write the logs into some other database while using [multiple databases](https://docs.djangoproject.com/en/3.2/topics/db/multi-db/)? If not, can you suggest any alternative work-arounds for this?

**Comment by saurabh0719** [comment]
`insert_log_into_database.py` file :

`def _insert_into_data_base(self, bulk_item)` - 
* In this function, when the API log details are written into the database, using `save()` Eg. `obj.save(using='some_db')` might solve the problem. 
* The database to write into could be another configuration in the `settings.py` file 

Do correct me if I've misunderstood something.

**Comment by vishalanandl177** [comment]
In the next version, there will be an option to change the default DB for DRF API Logger.

**Comment by vishalanandl177** [comment]
A new version is released with the fixes.
Please update to version 1.0.7
You can specify the database where to store DRF API Logs by setting DRF_API_LOGGER_DEFAULT_DATABASE  variable in the settings.py file.

Please read the docs for more information.
