### ISSUE TITLE
Feature to log only APIs with long execution time

### ISSUE THREAD

**Issue by Wenrong108** [vishalanandl177/DRF-API-Logger#19]
Hi, @vishalanandl177 
Thanks for your great library to log DRF apis. 

Could you do me a favor? 
I want to log only APIs with only long responsive time. How can I set config or customize middleware?

Hope your kind answer.

Thank you!

**Comment by vishalanandl177** [comment]
Hi, @Wenrong108 
To log only APIs having higher response time, please add `DRF_API_LOGGER_SIGNAL = True`.
And subscribe to listener.

In the listener you can check for execution_time.

For example, If execution_time > .200, then add insert into the database.

You need to create your own Model where you have to insert these slow APIs. You can just copy the DRF API Logger model as well.

For more information please check th documents.

Please let me know if you have any queries and difficulties.

**Comment by alex-malioukov** [comment]
Hello, @vishalanandl177 
I want same, also, I want to use not only DRF API logger model, but also chart in admin
How can I log only long time APIs and show chart in admin side?
Regards.

**Comment by vishalanandl177** [comment]
Please hold on for the next release, I'll add the "slow APIs" section in the Admin panel with configurable parameters.

**Comment by vishalanandl177** [comment]
Closing issue.
Feel free to reopen, if require any help.
