### ISSUE TITLE
Throws exception if Host header is missing

### ISSUE THREAD

**Issue by debfx** [vishalanandl177/DRF-API-Logger#2]
drf-api-logger throws an exception where there is no Host header in the request.

```
api_logger_middleware.py", line 93, in __call__
    host = request.META['HTTP_HOST']
KeyError: 'HTTP_HOST'
```

I noticed this when running unit tests with the api logger enabled.

**Comment by vishalanandl177** [comment]
Each API call is always going to have HTTP_HOST but during testing, it won't be available. I'll resolve this issue ASAP.

**Comment by vishalanandl177** [comment]
Did you use the `python manage.py test` to run unit tests?

**Comment by debfx** [comment]
> Did you use the `python manage.py test` to run unit tests?

Yes.

Though this can also happen when an HTTP client doesn't send a Host header and DJANGO_DOMAINS contains either `localhost` (missing Host header seems to be mapped to localhost in Django) or `*`.

So just setting `host` to `'localhost'` might be a solution if `HTTP_HOST` is missing.

**Comment by vishalanandl177** [comment]
Can you send me the list of middlewars? It seems you have used `'drf_api_logger.middleware.api_logger_middleware.APILoggerMiddleware',` before django middlewares

**Comment by vishalanandl177** [comment]
It should look something like this.

`MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'drf_api_logger.middleware.api_logger_middleware.APILoggerMiddleware',  # Always add this after django middleware
]`

**Comment by debfx** [comment]
`'drf_api_logger.middleware.api_logger_middleware.APILoggerMiddleware'` gets inserted at the end, after:

```
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_structlog.middlewares.RequestMiddleware',
]
```

**Comment by vishalanandl177** [comment]
During the testing, I'm not finding any logger issue. Can you explain the issue?

**Comment by debfx** [comment]
With DEBUG=True in the settings making a request against a DRF view without setting a Host header triggers this exception for me: `curl -v -H "Host:" 'http://127.0.0.1:8000/api/foo/bar/'`

You can see here that Django itself doesn't except `HTTP_HOST` header to always exist: https://github.com/django/django/blob/master/django/http/request.py#L118

**Comment by debfx** [comment]
Maybe replacing
```
            protocol = 'http'
            if request.is_secure():
                protocol = 'https'
            host = request.META['HTTP_HOST']
            api = '%s://%s%s' % (protocol, host, path,)
```
with
```
            api = request.get_raw_uri()
```
would be an option?

**Comment by vishalanandl177** [comment]
The code has been fixed.
Use pip install drf-api-logger==0.0.7

Set DRF_API_LOGGER_PATH_TYPE = 'RAW_URI' in settings.py

Considering we are accessing the following URL: http://127.0.0.1:8000/api/v1/?page=123 
DRF_API_LOGGER_PATH_TYPE possible values are:

1. ABSOLUTE (Default) :

Function used request.build_absolute_uri()

Output: http://127.0.0.1:8000/api/v1/?page=123

2. FULL_PATH

Function used request.get_full_path()

Output: /api/v1/?page=123

3. RAW_URI

Function used request.get_raw_uri()

Output: http://127.0.0.1:8000/api/v1/?page=123

Note: Similar to ABSOLUTE but skip allowed hosts protection, so may return insecure URI.
