### ISSUE TITLE
Filter request logs by users

### ISSUE THREAD

**Issue by Kelvin4664** [vishalanandl177/DRF-API-Logger#20]
One functionality i'll find useful is the ability to filter requests by a certain user for debugging purpose.
Perhaps an api is slow or failing for a certain user. Not sure if this is desirable for the entire project. I'll like to open a PR for it if it is. @vishalanandl177

**Comment by vishalanandl177** [comment]
Try using APILoggerModel if your project and analyze slow or failing conditions. 

Use
`
from drf_api_logger.models import APILogsModel
`

And do some queries.

`
slow_queries = APILogsModel.objects.filter(execution_time__gte=0.2)  # 0.2 second
`
