### ISSUE TITLE
Empy request body

### ISSUE THREAD

**Issue by ysomad** [vishalanandl177/DRF-API-Logger#21]
Got empty body in every request in Django Admin logs
<img width="828" alt="Screenshot 2021-06-15 at 3 12 47 PM" src="https://user-images.githubusercontent.com/49870662/122018420-0a60ee80-cded-11eb-97e9-2d8357727cdd.png">

**Comment by vishalanandl177** [comment]
Try sending content type in the request header.
Expected values (application/json or application/vnd.api+json)

**Comment by vishalanandl177** [comment]
Expected request body to be JSON. Otherwise, it will be empty.

**Comment by ysomad** [comment]
ok, thank you
is there any chances to get this work with multipart/form-data?

**Comment by vishalanandl177** [comment]
No. It will work only for content type application/json or application/vnd.api+json.
