### ISSUE TITLE
Logger only one api

### ISSUE THREAD

**Issue by serSok** [vishalanandl177/DRF-API-Logger#25]
Can you prompt, if need logger only for some api - how I can do it? exist DRF_API_LOGGER_SKIP_NAMESPACE and DRF_API_LOGGER_SKIP_URL_NAME, but all enumerate - its bad and can something forgot.

**Comment by vishalanandl177** [comment]
In the next version I'll add an option to log only selected APIs.

**Comment by vishalanandl177** [comment]
Closing.

Next version will have the option to log only API settings.
