### ISSUE TITLE
404 when used with apache

### ISSUE THREAD

**Issue by SecretUnicorn** [vishalanandl177/DRF-API-Logger#27]
The issue still persists therefore I reopen the issue. Check the new comment on the related issue. #23 

Thanks in advance...

**Comment by vishalanandl177** [comment]
Soon I'll deploy with the fixes.

**Comment by vishalanandl177** [comment]
Hi @SecretUnicorn.
I've tried in Apache server on Ubuntu OS multiple times, The library worked as expected.

Can you please give me more info so I can get into the core problem?

**Comment by vishalanandl177** [comment]
Due to inactivity
