### ISSUE TITLE
How to use DRF-API-Logger with DEBUG=FALSE?

### ISSUE THREAD

**Issue by vishal2develop** [vishalanandl177/DRF-API-Logger#28]
How to log API failures that arent handled by try-catch blocks?

**Comment by vishalanandl177** [comment]
Hi @vishal2develop 
I've tried doing the changes you have specified and integrated into 3 projects.
The developers working on these projects, don't like the changes and it caused some database related problems.
Please do this change from your end as this is an open-source project.

Thanks for your time.

**Comment by OllyPage** [comment]
A reasonable solution here would be to provide a custom DRF exception handler (https://www.django-rest-framework.org/api-guide/exceptions/#custom-exception-handling) that returns a rest_framework.exceptions.server_error (application/json). This will end up in the logs as a 500
```python
def drf_exception_handler(exc, context):
    """ Exception handler to provide valid json 500 errors """
    response = exception_handler(exc, context)
    if response is None:
        # # then it is an unhandled, i.e. 500
        request = context['request']
        return rest_framework.exceptions.server_error(request)
```
