### ISSUE TITLE
Feature Request: Enable for specific endpoints only

### ISSUE THREAD

**Issue by cleder** [vishalanandl177/DRF-API-Logger#3]
Use case:
In Production, I want to deprecate an API endpoint. For this I need to know whether there are still clients that use this endpoint. I do not want any overhead for other endpoints.

**Comment by vishalanandl177** [comment]
You can skip the url to be logged into the database or you can skip the entire app using namespace to be logged.

Skip namespace:
You can skip the entire app to be logged into the database by specifying namespace of the app as list.

DRF_API_LOGGER_SKIP_NAMESPACE = ['APP_NAMESPACE1', 'APP_NAMESPACE2']


Skip URL Name:
You can also skip any API to be logged by using url_name of the API.

DRF_API_LOGGER_SKIP_URL_NAME = ['url_name1', 'url_name2']


Does this going to solve your problem?
Please let me know any suggestions.


If you want to check of any user is using a specific API or not (this one is about to deprecate), just search the API end point in DRF Logger in admin panel.
