### ISSUE TITLE
Increase api field length

### ISSUE THREAD

**Issue by jatindergit** [vishalanandl177/DRF-API-Logger#31]
There are few apis which consists of long query params like
{{protocol}}://{{base_url}}/api/v1/configurations/area-templates/?search=searchstring&service=6&sub_location=9&sub_location=8&sub_location=7&fields=name,id&service_location=2&service_location=3&section=1&section=2&section=3&section=4&section=5&section=6&section=7&section=8&section=9&section=10&section=11&section=12&section=13&section=14&section=15&section=16&section=17&section=18&section=19&section=20&section=21&section=22&no_page

but according to the model field, this can only save 512 chars and raise 
*** django.db.utils.DataError: value too long for type character varying(512)

    class APILogsModel(BaseModel):
        api = models.CharField(max_length=512, help_text='API URL')

**Comment by jatindergit** [comment]
@vishalanandl177 Please look into this. thanks

**Comment by vishalanandl177** [comment]
Hi @jatindergit.
This will be fixed in the upcoming new version.

**Comment by jatindergit** [comment]
Thanks @vishalanandl177 
btw, when you are going to release it?

**Comment by vishalanandl177** [comment]
In 1 to 2 days, depending on the testing process.

**Comment by vishalanandl177** [comment]
Please install version 1.0.9
