### ISSUE TITLE
Store Log in cloudwatch

### ISSUE THREAD

**Issue by chiragkanhasoft** [vishalanandl177/DRF-API-Logger#33]
hello,

is it possible to store log in aws cloudwatch instead of the database? I am trying to achieve it using watchtower

**Comment by vishalanandl177** [comment]
Yes, it's possible.

Watchtower is a good library for this but it won't be the same as DEF-API-Logger.
I'll suggest you use DRF-API-Logger signals and manually log the data into a different database (for example Elasticsearch).

To log the data into Cloudwatch, use Watchtower for now. Soon I'll add a feature to log into CloudWatch as well.

**Comment by vishalanandl177** [comment]
Feel free to reopen.
