### ISSUE TITLE
Registrar only one or more methods

### ISSUE THREAD

**Issue by mowiwi** [vishalanandl177/DRF-API-Logger#34]
Can you prompt, if need logger only for some method (POST or PUT) or multiple methods (POST and PUT) - how I can do it?

**Comment by vishalanandl177** [comment]
Sure,
In up coming new version, I'll add this as an optional feature.

**Comment by vishalanandl177** [comment]
Hi @mowiwi 

If you want to log only some selected request methods, now you can do so.
Just specify DRF_API_LOGGER_METHODS = ['GET', 'POST', 'DELETE', 'PUT']  in the settings.

This feature is now available from version 1.0.10
