### ISSUE TITLE
Feature: Option to clear logs in admin

### ISSUE THREAD

**Issue by subodhk01** [vishalanandl177/DRF-API-Logger#38]
There should be an option to clear logs in Django admin. Maybe through Django admin actions

**Comment by vishalanandl177** [comment]
You can delete the logs by multi-selection from the admin panel.

**Comment by subodhk01** [comment]
But we can't delete thousands of instances at one time from admin panel

**Comment by vishalanandl177** [comment]
It's better if you manually archive the older data.

**Comment by subodhk01** [comment]
Can we add an export to csv admin action maybe?

**Comment by vishalanandl177** [comment]
Sure. I'll add the option to export the data based on the selected filters.
