### ISSUE TITLE
How to filter specific user using JWT?

### ISSUE THREAD

**Issue by LJiHye** [vishalanandl177/DRF-API-Logger#39]
## Overview

The `JWT` token is stored in the `headers` as follows.

**headers:**
```JSON
{
"AUTHORIZATION": "Bearer [JWT]",
}
```

When a user sends a `GET /log` request, I want to filter the `APILogsModel` based on `user_id`. (i.e. users can only see their own request history)

**Pseudo code:**
```python
class LogView(generics.ListAPIView):
    serializer_class = LogSerializer

    def get_queryset(self):
        token_str = self.request.META.get("HTTP_AUTHORIZATION", " ").split(" ")[1]
        access_token = AccessToken(token_str)

        ##################################################
        Filter by access_token
        ##################################################

        return queryset
```

## Problem

There is no field for user information in `APILogsModel`. Therefore, it must be extracted from the `JWT` stored in `headers`. However, it seems inefficient to extract it from all `headers` every time a request comes in.

## Conclusion

Is there any other efficient way? (Is it possible to override a model or middleware?)

**Comment by vishalanandl177** [comment]
Hi @LJiHye,

I suggest you to create a separate model (table) to store user-related information that you required (not all) and store the access log there, by subscribing to the API log signals.
Actually, Authorization is supposed to be hidden and not even the developers should know about the API-related user's information.

**Comment by LJiHye** [comment]
@vishalanandl177 

Thank you for answer. I seem to know a little bit 🙂
However, I'm not familiar with this project yet, so I don't know what to do with it.

So, how can the custom model be set in `settings.py`? And do I have to override the default middleware `APILoggerMiddleware` as well?
