### ISSUE TITLE
api field should be a TextField

### ISSUE THREAD

**Issue by jatindergit** [vishalanandl177/DRF-API-Logger#41]
@vishalanandl177 
I thing you should update `api` field in `APILogsModel` into `TextField`. The reason is, when we use `ModelMultipleChoiceFilter` in filterset class, it creates extra long urls like, `/api/v1/events/inspections/widgets/?&client=6&client=5&client=2&widget=top_service_locations`
Right now the `max_length=1024` of `api` field and if URL goes long than 1024, you package will throw error.
Thanks!

**Comment by vishalanandl177** [comment]
Usually, developers do analytics on these logs.
If you use a text field and add an index, if I'm not wrong, still the query will be a little slow because we have to specify a fixed-length on a text field to add an index.
So filter queries will be slow to do analytics.

**Comment by jatindergit** [comment]
Agreed
