### ISSUE TITLE
DRF_API_LOGGER_EXCLUDE_KEYS

### ISSUE THREAD

**Issue by Comprise** [vishalanandl177/DRF-API-Logger#43]
Hi guys.
There is a suggestion to leave the user the ability to change the default exceptions
https://github.com/vishalanandl177/DRF-API-Logger/blob/8602734104e635c2357836a06b6537341bebf883/drf_api_logger/utils.py#L4-L7
``` python 
SENSITIVE_KEYS = settings.DRF_API_LOGGER_EXCLUDE_KEYS
```

**Comment by vishalanandl177** [comment]
You can use 
`DRF_API_LOGGER_EXCLUDE_KEYS = []`
