### ISSUE TITLE
 Unicode Escape problem

### ISSUE THREAD

**Issue by vbuoc** [vishalanandl177/DRF-API-Logger#53]
How can I fix problem with Unicode Escape?

<img width="1098" alt="Снимок экрана 2022-06-23 в 16 56 21" src="https://user-images.githubusercontent.com/26590755/175303845-27962029-0f6b-47db-b1ea-944e88e76059.png">

**Comment by ViokingTung** [comment]
https://github.com/vishalanandl177/DRF-API-Logger/blob/a6e1b34657467bc337730918cf1d003eb87f729d/drf_api_logger/middleware/api_logger_middleware.py#L136-L139
caused by `json.dump()`, you maybe set `ensure_ascii=False` can resvole this problem.
