### ISSUE TITLE
User Details to Logs

### ISSUE THREAD

**Issue by mallucodewizard** [vishalanandl177/DRF-API-Logger#71]
Is there any way to add user details to the logs for eg: username or user id.

**Comment by vishalanandl177** [comment]
As of now, it's not supported here, but I'll suggest you override the api_logger_middleware middleware or use signals to add more custom info before storing anywhere.

Let me know if you need help regarding this.

**Comment by AlexMorra** [comment]
But we need to add the username or user_id to the API logs model, not just in the middleware,

I think we need something like this:

api_logger_middleware.py
```
data = dict(
        username=request.user.username,   # an anonymous user has a default username (or the user ID, for example, if it has)
        api=mask_sensitive_data(api, mask_api_parameters=True),
        headers=mask_sensitive_data(headers),
        ...
)
````

models.py
```
class APILogsModel(BaseModel):
        username = models.TextField()
        api = models.CharField(max_length=1024, help_text='API URL')
        headers = models.TextField()
       ...
```

isn't it? I need help :)

**Comment by mallucodewizard** [comment]
yea 



> As of now, it's not supported here, but I'll suggest you override the api_logger_middleware middleware or use signals to add more custom info before storing anywhere.
> 
> Let me know if you need help regarding this.

yea i think overriding middleware might help but using signals wont because the kwargs doesnt contain the request object. if you could provide the request object in kwargs in next update it will be really helpful

**Comment by vishalanandl177** [comment]
Sure, I'll update this soon.
