### ISSUE TITLE
Remove old logs

### ISSUE THREAD

**Issue by gruberrro** [vishalanandl177/DRF-API-Logger#79]
To be honest I'm not sure if this feature is implemented, but would be great to have possibility to remove old records with some kind of setting...

**Comment by laugrean** [comment]
Or maybe auto-archive into backup table. 
This would help a lot, for statistics later on

**Comment by vishalanandl177** [comment]
I'm already planning this feature.
In the next release, it will be available.

**Comment by laugrean** [comment]
Any updates on this when this will be implemanted approximately?

**Comment by gruberrro** [comment]
JFYI we decided to run celery beat which is removing old records every 24h

**Comment by vishalanandl177** [comment]
Some enterprise companies suggested not to add removal of old logs as a part of the application.
This can cause issues in their compliance.
Removal of logs should be a separate application (or micro-service).
