### ISSUE TITLE
Does not log a malformed POST body

### ISSUE THREAD

**Issue by dfrankow** [vishalanandl177/DRF-API-Logger#8]
I am not sure, but I believe that if there is an error parsing a POST body, possibly it does not capture the body.

Here's what I see in the Django admin UI:

![image](https://user-images.githubusercontent.com/34655/110044340-95bae600-7d0e-11eb-9746-eab57ed6b98a.png)

Unfortunately, I'm not quite sure how to easily set up a reproducible test case in your code repo. Suggestions welcome.

**Comment by dfrankow** [comment]
And, when this error occurs, I'd love to see the POST body!

**Comment by vishalanandl177** [comment]
You probably get the same response from API as well. As we can see from the screenshot you shared, the response is not JSON.
You are using POST call with no JSON data (body). Use empty JSON {} and the call POST API.
The DRF API Logger is only for JSON-type data.
Use the postman client app to call the API and then compare the response from the DRF API Logger Admin panel.

If you want to log extra information that DRF API Logger cannot log, use signals and log the data manually.
How to use signals and how to log data in the DRF API Logger model? Check the README.md for more information.

**Comment by dfrankow** [comment]
The response is proper JSON. It's the request that has invalid JSON. Below is more info about an example.

Request 2 below is a POST request to DRF, and has a non-empty POST body that is not logged by DRF API Logger. Perhaps you're saying this library only logs valid JSON POST bodies. I'm saying that it would be helpful if it logged the POST body even if it is invalid JSON. In fact, that's *very* helpful because that's a case where I really want to see the body!

I would re-open this issue if I could. I'll read the README about how to try to use signals to log the body, but I would appreciate any help.

===========================

1. Sending a request that works, using [httpie](https://httpie.io/):

```
$ cat ok.json
{ "question": "?", "creator": "example", "name": "example name" }
$ cat ok.json | http POST http://localhost:8000/api/v1/polls/
HTTP/1.1 201 Created
...
{
    "category": "",
    "created_dt": "2021-03-05T14:37:02.627205Z",
    "creator": "example",
    "id": "ABR5OZIwAhQ",
    "name": "example name",
    "question": "?"
}
```

![image](https://user-images.githubusercontent.com/34655/110130121-4f0cd080-7d8e-11eb-9e6a-f477c0933df2.png)

2. Sending a request with a POST body that is invalid JSON (extra double quote):

```
$ cat not_ok.json
{ "question": "?", "creator": "example"", "name": "example name" }
$ cat not_ok.json | http POST http://localhost:8000/api/v1/polls/
HTTP/1.1 400 Bad Request
...
{
    "detail": "JSON parse error - Expecting ',' delimiter: line 1 column 40 (char 39)"
}
```

It had a POST body, but that body was not logged:

![image](https://user-images.githubusercontent.com/34655/110130773-0275c500-7d8f-11eb-8afb-e448f9100da6.png)
