### ISSUE TITLE
Storing Tracing ID in Database 

### ISSUE THREAD

**Issue by mimustafa** [vishalanandl177/DRF-API-Logger#87]
The logger has good options to enable tracing id but it is never saved in the database. It would be good enhancement if the tracing ID is stored in the database as well. So that it can be used as Correlation ID for linking it with other Django log apps and Django logging.

**Comment by vishalanandl177** [comment]
Hi @mimustafa,
You can create a custom model similar to [exiting model](https://github.com/vishalanandl177/DRF-API-Logger/blob/main/drf_api_logger/models.py) and use signal to capture and store all the API events.
