### ISSUE TITLE
storing user, view, view method, 

### ISSUE THREAD

**Issue by mimustafa** [vishalanandl177/DRF-API-Logger#88]
It would be a good enhancement if there is user id, view (e.g. apps.abc.XYZViewSet), view method (List),  stored in the database as well. Also if the API is divided into Host, Path,Query Parmas/data (that what is in body now).

**Comment by rkisdp** [comment]
Added in #90 pull request. Data is the payload which we send during making a request.

**Comment by stardust85** [comment]
I tried https://github.com/django-request/django-request and it does exactly what you want.
