### ISSUE TITLE
Add History Table to increase performance of the view

### ISSUE THREAD

**Issue by laugrean** [vishalanandl177/DRF-API-Logger#89]
It would be great to provide a optional feature where you can define if you want to to move data from the current table into a archive table to increase performance!

E.g. 
Live_data_keep = x days
all data which is beyond this, will be moved to the archive table. 
And would be great if you are there is an additional view for archive in the backend. 

This would increase performance dramatically.

**Comment by laugrean** [comment]
Hello, 

are there already any plans when this will be available? 

Thank you in advance!

**Comment by vishalanandl177** [comment]
Hello,

To enhance performance, kindly consider adding indexes or implementing partitioning according to your use case. For data archiving, please utilize an alternative service or set up CRON jobs as needed.

Thank you!
