### ISSUE TITLE
Add Username to log messages

### ISSUE THREAD

**Issue by rdomga** [vishalanandl177/DRF-API-Logger#9]
Please
Is it possible this package to add the username or user ID (if available) to the log messages?
Thank you in advance for your response

**Comment by vishalanandl177** [comment]
This package is for Rest APIs, so username should be available in headers
or body if client sent the same.

Please let me know if not clear.

**Comment by danielqba** [comment]
What about using JWT? How do I log the username to the DB? @vishalanandl177

**Comment by vishalanandl177** [comment]
You can log the username only if the username is coming as a part of the request. It may come in header or body.

If you want to do extra operation with the data to identify the username from jwt or request token, the subscribe to the DRF API Logger events and manually log the information to your own logging table.
