### ISSUE TITLE
Can not find static files as soon as I use this package

### ISSUE THREAD

**Issue by gijsriet** [vishalanandl177/DRF-API-Logger#91]
Hi,

I have an issue on my test server as soon as I implement drf-api-logger.

As soon as I use the package, on my test server, none of my static files can be found. When I comment out the package in installed apps everything is back to normal. None of the logs show anything useful for debugging this.

Has anyone encountered something similar or has an idea?

Django 4.2
I use a separate database for the api-logs
App running on Kubernetes.

**Comment by gijsriet** [comment]
Hi, thanks for your answer. Yeah I know about collectstatic :). The app has been running in production for over 5 years. The logs tell me nothing. Also the staticfiles are found when using findstatic, and nginx is not the isssue either. Just as soon as I add drf-api-logger, none of the static files can be found.

**Comment by gijsriet** [comment]
The problem is caused by this line here
`url_name = resolve(request.path_info).url_name`
in the middleware, where staticfile paths can not be resolved to a route.

**Comment by vishalanandl177** [comment]
Hi @gijsriet 
The fixes will be available in the next release.

**Comment by abe-101** [comment]
@vishalanandl177 any timeline on a release with this fix?
