### ISSUE TITLE
Package name in setup.py should be the same as your pip install `drf-api-logger`.

### ISSUE THREAD

**Issue by tsantor** [vishalanandl177/DRF-API-Logger#95]
Great package, but when you `pip install drf-api-logger` and then `pip list` packages installed, it identifies itself as `drf_api_logger` when it really should be `drf-api-logger` which was just installed.

**Comment by vishalanandl177** [comment]
I'll update this in the next release.

**Comment by vishalanandl177** [comment]
Available in the release 1.1.16
